# Generated by Django 3.1.5 on 2021-01-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workers_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фотография сотрудника'),
        ),
    ]
